#!/bin/bash -eu

#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

function filterExcludedAndGeneratedFiles {
    local excluded_files
    excluded_files=(
        ".git$"
        "(^|/)vendor/"
        "\.txt$"
        "\.md$"
        "\.rst$"
       "^Gopkg.lock$"
    )

    local filter
    filter=$(local IFS='|' ; echo "${excluded_files[*]}")

    read -ra files <<<"$@"
    for f in "${files[@]}"; do
        file=$(echo "$f" | grep -Ev "$filter" | sort -u)
        if [ -n "$file" ]; then
            head -n2 "$file" | grep -qE '// Code generated by' || echo "$file"
        fi
    done
}

candidates=$(git diff --name-only --diff-filter=ACMRTUXB HEAD | tr '\n' ' ')
if [[ -z "$candidates" ]]; then
    candidates=$(git diff-tree --no-commit-id --name-only --diff-filter=ACMRTUXB -r "HEAD^..HEAD" | tr '\n' ' ')
fi
files_to_check=$(filterExcludedAndGeneratedFiles "$candidates")
if [[ -z "$files_to_check" ]]; then
    echo "All files are excluded from having license headers"
    exit 0
fi

missing=$(echo "${files_to_check}" | sort -u | xargs ls -d 2>/dev/null | xargs grep -L "SPDX-License-Identifier" || true)
if [ -n "$missing" ]; then
    echo "The following files are missing SPDX-License-Identifier headers:"
    echo
    echo "$missing"
    echo
    echo "Please replace the Apache license header comment text with:"
    echo "SPDX-License-Identifier: Apache-2.0"
    exit 1
fi
