# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
- main

variables:
  GOVER: 1.14.3
  PATH: $(Agent.BuildDirectory)/go/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin

pool:
  vmImage: ubuntu-18.04

steps:
- task: GoTool@0
  inputs:
    version: $(GOVER)
  displayName: Install Go
- checkout: self
  path: 'src/fabric-lib-go'
  displayName: Checkout Fabric-Lib-Go Code
- script: make checks unit-tests GOTOOLS_BINDIR=$(Agent.BuildDirectory)/go/bin
  displayName: Run Checks and Unit Tests
